import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = 
  | "en" | "hi" | "kn" | "te" | "ta" | "ml" | "mr" | "gu" | "bn" | "pa" 
  | "es" | "fr" | "de" | "ar" | "zh" | "ja" | "ko" | "pt" | "ru" | "it";

export interface LanguageInfo {
  code: Language;
  name: string;
  nativeName: string;
  flag: string;
}

export const languages: LanguageInfo[] = [
  { code: "en", name: "English", nativeName: "English", flag: "🇺🇸" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी", flag: "🇮🇳" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ", flag: "🇮🇳" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు", flag: "🇮🇳" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்", flag: "🇮🇳" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം", flag: "🇮🇳" },
  { code: "mr", name: "Marathi", nativeName: "मराठी", flag: "🇮🇳" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી", flag: "🇮🇳" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা", flag: "🇮🇳" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ", flag: "🇮🇳" },
  { code: "es", name: "Spanish", nativeName: "Español", flag: "🇪🇸" },
  { code: "fr", name: "French", nativeName: "Français", flag: "🇫🇷" },
  { code: "de", name: "German", nativeName: "Deutsch", flag: "🇩🇪" },
  { code: "ar", name: "Arabic", nativeName: "العربية", flag: "🇸🇦" },
  { code: "zh", name: "Chinese", nativeName: "中文", flag: "🇨🇳" },
  { code: "ja", name: "Japanese", nativeName: "日本語", flag: "🇯🇵" },
  { code: "ko", name: "Korean", nativeName: "한국어", flag: "🇰🇷" },
  { code: "pt", name: "Portuguese", nativeName: "Português", flag: "🇧🇷" },
  { code: "ru", name: "Russian", nativeName: "Русский", flag: "🇷🇺" },
  { code: "it", name: "Italian", nativeName: "Italiano", flag: "🇮🇹" },
];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  currentLanguageInfo: LanguageInfo;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("edgeaihub-language");
      if (saved && languages.some(l => l.code === saved)) {
        return saved as Language;
      }
      const browserLang = navigator.language.split("-")[0] as Language;
      if (languages.some(l => l.code === browserLang)) {
        return browserLang;
      }
    }
    return "en";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("edgeaihub-language", lang);
    document.documentElement.lang = lang;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const currentLanguageInfo = languages.find(l => l.code === language) || languages[0];

  const t = (key: string): string => {
    const translations = getTranslations(language);
    return translations[key] || getTranslations("en")[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, currentLanguageInfo }}>
      {children}
    </LanguageContext.Provider>
  );
};

const baseTranslations: Record<string, string> = {
  // Navbar
  "nav.whyUs": "Why Us",
  "nav.samples": "Samples",
  "nav.aiShortFilms": "AI Short Films",
  "nav.howItWorks": "How It Works",
  "nav.blog": "Blog",
  // Hero
  "hero.badge.aiPowered": "AI-Powered",
  "hero.badge.conversionFocused": "Conversion-Focused",
  "hero.badge.globalQuality": "Global Quality",
  "hero.badge.fastDelivery": "Fast Delivery",
  "hero.title1": "Premium AI Video Ads",
  "hero.title2": "For Your Business",
  "hero.subtitle": "Stop wasting lakhs on agencies. Get studio-quality 30-second video ads powered by cutting-edge AI — faster, smarter, and at a fraction of the cost.",
  "hero.trust": "Trusted by 10,000+ businesses across India & worldwide",
  "hero.emailBtn": "Contact via Email",
  "hero.callBtn": "Call",
  "hero.stats.adsCreated": "Ads Created",
  "hero.stats.fastDelivery": "Fast Delivery",
  "hero.stats.countries": "Countries Served",
  "hero.stats.satisfaction": "Satisfaction",
  // CTA
  "cta.badge": "The Future of Video Advertising",
  "cta.title1": "Your Competitors Are Already",
  "cta.title2": "Using AI Ads",
  "cta.subtitle": "Every day you wait, you lose customers to businesses with better video content.",
  "cta.contact": "Contact us today for premium AI video ads.",
  "cta.whyChoose": "Why Choose edgeaihub?",
  "cta.point1": "Agencies charge lakhs — we're affordable",
  "cta.point2": "Weeks of waiting — we deliver in 24 hours",
  "cta.point3": "Inconsistent quality — we guarantee premium output",
  "cta.point4": "Complex processes — we make it effortless",
  "cta.noCommitments": "No commitments. Just start a conversation.",
  // Why Us
  "whyUs.badge": "The Smart Choice",
  "whyUs.title": "Why",
  "whyUs.subtitle": "Agencies charge lakhs. Freelancers disappoint. Generic tools fail. We deliver premium quality at affordable prices.",
  "whyUs.agencies.title": "Traditional Agencies",
  "whyUs.agencies.point1": "₹50,000 - ₹5,00,000 per video",
  "whyUs.agencies.point2": "2-4 weeks delivery time",
  "whyUs.agencies.point3": "Endless revision cycles",
  "whyUs.agencies.point4": "Complex contracts & commitments",
  "whyUs.freelancers.title": "Freelancers",
  "whyUs.freelancers.point1": "Inconsistent quality",
  "whyUs.freelancers.point2": "Unreliable timelines",
  "whyUs.freelancers.point3": "Limited creative options",
  "whyUs.freelancers.point4": "No scalability",
  "whyUs.genericAI.title": "Generic AI Tools",
  "whyUs.genericAI.point1": "Template-looking output",
  "whyUs.genericAI.point2": "No ad optimization",
  "whyUs.genericAI.point3": "Complex learning curve",
  "whyUs.genericAI.point4": "Poor conversion rates",
  "whyUs.edgeaihub.point1": "Affordable premium video ads",
  "whyUs.edgeaihub.point2": "24-hour delivery guaranteed",
  "whyUs.edgeaihub.point3": "Conversion-optimized templates",
  "whyUs.edgeaihub.point4": "Scale unlimited ads instantly",
  // Trust Section
  "trust.badge": "Your Trust Matters",
  "trust.title": "Quality &",
  "trust.titleHighlight": "Reliability",
  "trust.subtitle": "We take your brand seriously. Every ad goes through rigorous checks.",
  "trust.brandSafe.title": "Brand Safe",
  "trust.brandSafe.description": "Every ad is reviewed to ensure it aligns with your brand values and platform guidelines.",
  "trust.qualityChecked.title": "Quality Checked",
  "trust.qualityChecked.description": "Multi-layer quality assurance before delivery. No glitches, no errors, no compromises.",
  "trust.humanVerified.title": "Human Verified",
  "trust.humanVerified.description": "AI creates, humans verify. The perfect blend of efficiency and quality control.",
  "trust.secureProcess.title": "Secure Process",
  "trust.secureProcess.description": "Your business details and brand assets are handled with complete confidentiality.",
  // Footer
  "footer.tagline": "Premium AI Video Ads",
  "footer.description": "Premium AI Video Ads + Hollywood-quality AI Short Films for global brands.",
  "footer.ourServices": "Our Services",
  "footer.services.videoAds": "AI Video Ads",
  "footer.services.shortFilms": "AI Short Films",
  "footer.services.brandVideos": "Brand Videos",
  "footer.services.productAds": "Product Ads",
  "footer.industriesWeServe": "Industries We Serve",
  "footer.industries.fashion": "Fashion & Jewelry",
  "footer.industries.ecommerce": "E-commerce",
  "footer.industries.realestate": "Real Estate",
  "footer.industries.education": "Education",
  "footer.industries.restaurants": "Restaurants",
  "footer.industries.healthcare": "Healthcare",
  "footer.getInTouch": "Get in Touch",
  "footer.businessHours": "Mon-Sat, 9am-8pm IST",
  "footer.office": "Office",
  "footer.rights": "All rights reserved.",
  "footer.aiPowered": "AI-Powered",
  "footer.cinemaQuality": "Cinema Quality",
  "footer.globalService": "Global Service",
  "footer.quickLinks": "Quick Links",
  "footer.contact": "Contact",
  // Blog Section
  "blog.badge": "KNOWLEDGE HUB",
  "blog.title": "AI Video Marketing",
  "blog.titleHighlight": "Blog",
  "blog.subtitle": "Expert tips, strategies, and guides to help you create viral video ads and grow your business",
  "blog.readArticle": "Read Article",
  "blog.backToBlog": "Back to Blog",
  "blog.relatedArticles": "Related Articles",
  "blog.ctaTitle": "Ready to Create Your Own AI Video Ad?",
  "blog.ctaSubtitle": "Get a premium AI video ad with 24-hour delivery",
  "blog.category.aiMarketing": "AI Marketing",
  "blog.category.socialMedia": "Social Media",
  "blog.category.aiFilms": "AI Films",
  "blog.category.realEstate": "Real Estate",
  "blog.category.ecommerce": "E-commerce",
  "blog.category.luxury": "Luxury",
  "blog.minRead": "min read",
  "blog.share": "Share",
  // How It Works
  "howItWorks.badge": "Simple Process",
  "howItWorks.title": "How It",
  "howItWorks.titleHighlight": "Works",
  "howItWorks.subtitle": "Three simple steps. Zero complexity. Your ad delivered fast.",
  "howItWorks.step1.title": "Contact Us",
  "howItWorks.step1.description": "Email us or call +91 7207926206. Tell us about your business and goals.",
  "howItWorks.step2.title": "Share Details",
  "howItWorks.step2.description": "Send your business info, logo, key message, and any preferences you have.",
  "howItWorks.step3.title": "Receive Your Ad",
  "howItWorks.step3.description": "Get your premium AI video ad within 24 hours. Ready to run on any platform.",
  // Sample Videos
  "samples.badge": "Real Examples",
  "samples.title": "See Real",
  "samples.titleHighlight": "AI Ads We Create",
  "samples.subtitle": "These are actual sample videos. This is the exact quality you will receive.",
  "samples.ecommerce": "Jewellery & Fashion That Sells 10x Faster",
  "samples.ecommerceCategory": "E-commerce & D2C Ads",
  "samples.restaurant": "Hot Coffee That Sells Itself",
  "samples.restaurantCategory": "Café & Restaurant Ads",
  "samples.education": "Coaching Ads That Fill Every Seat",
  "samples.educationCategory": "Education & EdTech",
  "samples.realestate": "Real Estate Showcase",
  "samples.realestateCategory": "Property",
  "samples.fashion": "Runway-Ready Ads That Convert",
  "samples.fashionCategory": "Fashion & D2C Brands",
  "samples.tech": "Tech Startup Demo",
  "samples.techCategory": "SaaS / App",
  "samples.cta": "Want an ad like this for your business?",
  // Industries
  "industries.badge": "Universal Solution",
  "industries.title": "Industries We",
  "industries.titleHighlight": "Serve",
  "industries.subtitle": "From local shops to global brands — our AI adapts to every industry.",
  "industries.ecommerce": "E-commerce & D2C",
  "industries.ecommerceDesc": "Product launches, offers, brand videos",
  "industries.restaurants": "Restaurants & Cafes",
  "industries.restaurantsDesc": "Menu highlights, delivery promos",
  "industries.coaches": "Coaches & Educators",
  "industries.coachesDesc": "Course promos, testimonials",
  "industries.realestate": "Real Estate",
  "industries.realestateDesc": "Property showcases, virtual tours",
  "industries.healthcare": "Healthcare & Wellness",
  "industries.healthcareDesc": "Clinic promos, service highlights",
  "industries.professional": "Professional Services",
  "industries.professionalDesc": "Law firms, consultants, agencies",
  "industries.automotive": "Automotive",
  "industries.automotiveDesc": "Dealerships, rentals, services",
  "industries.startups": "Startups & Tech",
  "industries.startupsDesc": "App demos, SaaS explainers",
  "industries.entertainment": "Entertainment & Media",
  "industries.entertainmentDesc": "Movie trailers, OTT promos, music videos",
  "industries.luxury": "Luxury & Jewelry",
  "industries.luxuryDesc": "Diamonds • Gold • Fashion Jewelry • Watches",
  "industries.beauty": "Beauty & Skincare",
  "industries.beautyDesc": "Cosmetics • Skincare • Wellness • Spa",
  "industries.designer": "Designer Fashion",
  "industries.designerDesc": "Haute Couture • Bridal • Luxury Apparel",
  "industries.footer": "Don't see your industry?",
  "industries.footerHighlight": "We create ads for any business worldwide.",
  // ROI Section
  "roi.badge": "The Math Makes Sense",
  "roi.title": "Transform Your Investment Into",
  "roi.titleHighlight": "Massive ROI",
  "roi.subtitle": "Smart business owners understand: better creatives = better performance = higher profits. Here's how edgeaihub multiplies your returns.",
  "roi.subtitleBold": "better creatives = better performance = higher profits",
  "roi.step1.title": "Smart Investment",
  "roi.step1.description": "Create premium video ads at minimal cost — test multiple creatives rapidly.",
  "roi.step2.title": "Better Creatives",
  "roi.step2.description": "AI-optimized visuals and hooks that grab attention in the first 3 seconds.",
  "roi.step3.title": "Higher CTR",
  "roi.step3.description": "Quality creatives = higher click-through rates on every ad platform.",
  "roi.step4.title": "Lower Ad Costs",
  "roi.step4.description": "Better performance = lower CPC = more conversions per rupee spent.",
  "roi.result.title": "Result:",
  "roi.result.highlight": "10x - 100x Return on Investment",
  "roi.result.description": "Businesses using edgeaihub report 50-70% lower cost per acquisition and 3x higher engagement rates compared to traditional video production.",
  "roi.result.lowerCost": "50-70% lower cost per acquisition",
  "roi.result.engagement": "3x higher engagement rates",
  "roi.investment": "Affordable",
  "roi.investmentLabel": "Your Investment",
  "roi.returns": "10x-100x",
  "roi.returnsLabel": "Potential Returns",
  // Common
  "common.call": "Call",
  "common.email": "Email",
};

const getTranslations = (lang: Language): Record<string, string> => {
  const translations: Record<Language, Record<string, string>> = {
    en: { ...baseTranslations },
    hi: {
      ...baseTranslations,
      "nav.whyUs": "हमें क्यों चुनें",
      "nav.samples": "नमूने",
      "nav.aiShortFilms": "AI शॉर्ट फिल्म्स",
      "nav.howItWorks": "कैसे काम करता है",
      "nav.blog": "ब्लॉग",
      "hero.badge.aiPowered": "AI-संचालित",
      "hero.badge.conversionFocused": "रूपांतरण-केंद्रित",
      "hero.badge.globalQuality": "वैश्विक गुणवत्ता",
      "hero.badge.fastDelivery": "तेज़ डिलीवरी",
      "hero.title1": "प्रीमियम AI वीडियो विज्ञापन",
      "hero.title2": "आपके व्यवसाय के लिए",
      "hero.subtitle": "एजेंसियों पर लाखों खर्च करना बंद करें। AI द्वारा संचालित स्टूडियो-गुणवत्ता वाले 30-सेकंड के वीडियो विज्ञापन प्राप्त करें — तेज़, स्मार्ट और कम लागत में।",
      "hero.trust": "भारत और दुनिया भर में 10,000+ व्यवसायों द्वारा विश्वसनीय",
      "hero.emailBtn": "ईमेल से संपर्क करें",
      "hero.callBtn": "कॉल करें",
      "hero.stats.adsCreated": "विज्ञापन बनाए गए",
      "hero.stats.fastDelivery": "तेज़ डिलीवरी",
      "hero.stats.countries": "देश सेवित",
      "hero.stats.satisfaction": "संतुष्टि",
      "cta.badge": "वीडियो विज्ञापन का भविष्य",
      "cta.title1": "आपके प्रतियोगी पहले से ही",
      "cta.title2": "AI विज्ञापनों का उपयोग कर रहे हैं",
      "cta.subtitle": "हर दिन जब आप इंतजार करते हैं, आप ग्राहकों को बेहतर वीडियो सामग्री वाले व्यवसायों से खो देते हैं।",
      "cta.contact": "प्रीमियम AI वीडियो विज्ञापनों के लिए आज ही संपर्क करें।",
      "cta.whyChoose": "edgeaihub क्यों चुनें?",
      "cta.point1": "एजेंसियां लाखों लेती हैं — हम किफायती हैं",
      "cta.point2": "हफ्तों का इंतजार — हम 24 घंटों में डिलीवर करते हैं",
      "cta.point3": "असंगत गुणवत्ता — हम प्रीमियम आउटपुट की गारंटी देते हैं",
      "cta.point4": "जटिल प्रक्रियाएं — हम इसे आसान बनाते हैं",
      "cta.noCommitments": "कोई प्रतिबद्धता नहीं। बस बातचीत शुरू करें।",
      "whyUs.badge": "स्मार्ट विकल्प",
      "whyUs.title": "क्यों",
      "whyUs.subtitle": "एजेंसियां लाखों लेती हैं। फ्रीलांसर निराश करते हैं। सामान्य टूल असफल होते हैं। हम किफायती कीमतों पर प्रीमियम गुणवत्ता देते हैं।",
      "whyUs.agencies.title": "पारंपरिक एजेंसियां",
      "whyUs.agencies.point1": "₹50,000 - ₹5,00,000 प्रति वीडियो",
      "whyUs.agencies.point2": "2-4 सप्ताह डिलीवरी समय",
      "whyUs.agencies.point3": "अंतहीन संशोधन चक्र",
      "whyUs.agencies.point4": "जटिल अनुबंध और प्रतिबद्धताएं",
      "whyUs.freelancers.title": "फ्रीलांसर",
      "whyUs.freelancers.point1": "असंगत गुणवत्ता",
      "whyUs.freelancers.point2": "अविश्वसनीय समयसीमा",
      "whyUs.freelancers.point3": "सीमित रचनात्मक विकल्प",
      "whyUs.freelancers.point4": "कोई स्केलेबिलिटी नहीं",
      "whyUs.genericAI.title": "सामान्य AI टूल्स",
      "whyUs.genericAI.point1": "टेम्पलेट जैसा आउटपुट",
      "whyUs.genericAI.point2": "कोई विज्ञापन अनुकूलन नहीं",
      "whyUs.genericAI.point3": "जटिल सीखने की प्रक्रिया",
      "whyUs.genericAI.point4": "खराब रूपांतरण दर",
      "whyUs.edgeaihub.point1": "किफायती प्रीमियम वीडियो विज्ञापन",
      "whyUs.edgeaihub.point2": "24 घंटे डिलीवरी गारंटी",
      "whyUs.edgeaihub.point3": "रूपांतरण-अनुकूलित टेम्पलेट्स",
      "whyUs.edgeaihub.point4": "तुरंत असीमित विज्ञापन स्केल करें",
      "trust.badge": "आपका विश्वास मायने रखता है",
      "trust.title": "गुणवत्ता और",
      "trust.titleHighlight": "विश्वसनीयता",
      "trust.subtitle": "हम आपके ब्रांड को गंभीरता से लेते हैं। हर विज्ञापन कठोर जांच से गुजरता है।",
      "trust.brandSafe.title": "ब्रांड सुरक्षित",
      "trust.brandSafe.description": "हर विज्ञापन की समीक्षा की जाती है ताकि यह आपके ब्रांड मूल्यों और प्लेटफॉर्म दिशानिर्देशों के अनुरूप हो।",
      "trust.qualityChecked.title": "गुणवत्ता जांची गई",
      "trust.qualityChecked.description": "डिलीवरी से पहले मल्टी-लेयर गुणवत्ता आश्वासन। कोई गड़बड़ नहीं, कोई त्रुटि नहीं, कोई समझौता नहीं।",
      "trust.humanVerified.title": "मानव सत्यापित",
      "trust.humanVerified.description": "AI बनाता है, मनुष्य सत्यापित करते हैं। दक्षता और गुणवत्ता नियंत्रण का सही मिश्रण।",
      "trust.secureProcess.title": "सुरक्षित प्रक्रिया",
      "trust.secureProcess.description": "आपके व्यवसाय विवरण और ब्रांड संपत्तियां पूर्ण गोपनीयता के साथ संभाली जाती हैं।",
      "footer.tagline": "प्रीमियम AI वीडियो विज्ञापन",
      "footer.description": "वैश्विक ब्रांडों के लिए प्रीमियम AI वीडियो विज्ञापन + हॉलीवुड-गुणवत्ता AI शॉर्ट फिल्म्स।",
      "footer.ourServices": "हमारी सेवाएं",
      "footer.services.videoAds": "AI वीडियो विज्ञापन",
      "footer.services.shortFilms": "AI शॉर्ट फिल्म्स",
      "footer.services.brandVideos": "ब्रांड वीडियो",
      "footer.services.productAds": "उत्पाद विज्ञापन",
      "footer.industriesWeServe": "हम किन उद्योगों की सेवा करते हैं",
      "footer.industries.fashion": "फैशन और आभूषण",
      "footer.industries.ecommerce": "ई-कॉमर्स",
      "footer.industries.realestate": "रियल एस्टेट",
      "footer.industries.education": "शिक्षा",
      "footer.industries.restaurants": "रेस्तरां",
      "footer.industries.healthcare": "स्वास्थ्य सेवा",
      "footer.getInTouch": "संपर्क करें",
      "footer.businessHours": "सोम-शनि, सुबह 9 - रात 8 IST",
      "footer.office": "कार्यालय",
      "footer.rights": "सर्वाधिकार सुरक्षित।",
      "footer.aiPowered": "AI-संचालित",
      "footer.cinemaQuality": "सिनेमा गुणवत्ता",
      "footer.globalService": "वैश्विक सेवा",
      "footer.quickLinks": "त्वरित लिंक",
      "footer.contact": "संपर्क",
      "blog.badge": "ज्ञान केंद्र",
      "blog.title": "AI वीडियो मार्केटिंग",
      "blog.titleHighlight": "ब्लॉग",
      "blog.subtitle": "वायरल वीडियो विज्ञापन बनाने और अपना व्यवसाय बढ़ाने के लिए विशेषज्ञ सुझाव, रणनीतियाँ और गाइड",
      "blog.readArticle": "लेख पढ़ें",
      "blog.backToBlog": "ब्लॉग पर वापस",
      "blog.relatedArticles": "संबंधित लेख",
      "blog.ctaTitle": "अपना खुद का AI वीडियो विज्ञापन बनाने के लिए तैयार हैं?",
      "blog.ctaSubtitle": "24 घंटे की डिलीवरी के साथ प्रीमियम AI वीडियो विज्ञापन प्राप्त करें",
      "blog.category.aiMarketing": "AI मार्केटिंग",
      "blog.category.socialMedia": "सोशल मीडिया",
      "blog.category.aiFilms": "AI फिल्म्स",
      "blog.category.realEstate": "रियल एस्टेट",
      "blog.category.ecommerce": "ई-कॉमर्स",
      "blog.category.luxury": "लग्जरी",
      "blog.minRead": "मिनट पढ़ें",
      "blog.share": "साझा करें",
      // How It Works
      "howItWorks.badge": "सरल प्रक्रिया",
      "howItWorks.title": "यह कैसे",
      "howItWorks.titleHighlight": "काम करता है",
      "howItWorks.subtitle": "तीन सरल कदम। शून्य जटिलता। आपका विज्ञापन तेजी से वितरित।",
      "howItWorks.step1.title": "हमसे संपर्क करें",
      "howItWorks.step1.description": "हमें ईमेल करें या +91 7207926206 पर कॉल करें। अपने व्यवसाय और लक्ष्यों के बारे में बताएं।",
      "howItWorks.step2.title": "विवरण साझा करें",
      "howItWorks.step2.description": "अपनी व्यावसायिक जानकारी, लोगो, मुख्य संदेश और कोई भी प्राथमिकताएं भेजें।",
      "howItWorks.step3.title": "अपना विज्ञापन प्राप्त करें",
      "howItWorks.step3.description": "24 घंटों के भीतर अपना प्रीमियम AI वीडियो विज्ञापन प्राप्त करें। किसी भी प्लेटफॉर्म पर चलाने के लिए तैयार।",
      // Sample Videos
      "samples.badge": "वास्तविक उदाहरण",
      "samples.title": "देखें असली",
      "samples.titleHighlight": "AI विज्ञापन जो हम बनाते हैं",
      "samples.subtitle": "ये वास्तविक नमूना वीडियो हैं। यही वह सटीक गुणवत्ता है जो आपको मिलेगी।",
      "samples.ecommerce": "आभूषण और फैशन जो 10 गुना तेजी से बिकता है",
      "samples.ecommerceCategory": "ई-कॉमर्स और D2C विज्ञापन",
      "samples.restaurant": "गर्म कॉफी जो खुद बिकती है",
      "samples.restaurantCategory": "कैफे और रेस्तरां विज्ञापन",
      "samples.education": "कोचिंग विज्ञापन जो हर सीट भरते हैं",
      "samples.educationCategory": "शिक्षा और एडटेक",
      "samples.realestate": "रियल एस्टेट शोकेस",
      "samples.realestateCategory": "संपत्ति",
      "samples.fashion": "रनवे-तैयार विज्ञापन जो कन्वर्ट करते हैं",
      "samples.fashionCategory": "फैशन और D2C ब्रांड",
      "samples.tech": "टेक स्टार्टअप डेमो",
      "samples.techCategory": "SaaS / ऐप",
      "samples.cta": "अपने व्यवसाय के लिए ऐसा विज्ञापन चाहते हैं?",
      // Industries
      "industries.badge": "सार्वभौमिक समाधान",
      "industries.title": "उद्योग जिनकी हम",
      "industries.titleHighlight": "सेवा करते हैं",
      "industries.subtitle": "स्थानीय दुकानों से लेकर वैश्विक ब्रांडों तक — हमारी AI हर उद्योग के अनुकूल है।",
      "industries.ecommerce": "ई-कॉमर्स और D2C",
      "industries.ecommerceDesc": "उत्पाद लॉन्च, ऑफर, ब्रांड वीडियो",
      "industries.restaurants": "रेस्तरां और कैफे",
      "industries.restaurantsDesc": "मेनू हाइलाइट्स, डिलीवरी प्रोमो",
      "industries.coaches": "कोच और शिक्षक",
      "industries.coachesDesc": "कोर्स प्रोमो, प्रशंसापत्र",
      "industries.realestate": "रियल एस्टेट",
      "industries.realestateDesc": "संपत्ति शोकेस, वर्चुअल टूर",
      "industries.healthcare": "स्वास्थ्य सेवा और वेलनेस",
      "industries.healthcareDesc": "क्लिनिक प्रोमो, सेवा हाइलाइट्स",
      "industries.professional": "पेशेवर सेवाएं",
      "industries.professionalDesc": "कानून फर्म, सलाहकार, एजेंसियां",
      "industries.automotive": "ऑटोमोटिव",
      "industries.automotiveDesc": "डीलरशिप, रेंटल, सेवाएं",
      "industries.startups": "स्टार्टअप और टेक",
      "industries.startupsDesc": "ऐप डेमो, SaaS एक्सप्लेनर",
      "industries.entertainment": "मनोरंजन और मीडिया",
      "industries.entertainmentDesc": "मूवी ट्रेलर, OTT प्रोमो, म्यूजिक वीडियो",
      "industries.luxury": "लग्जरी और ज्वेलरी",
      "industries.luxuryDesc": "हीरे • सोना • फैशन ज्वेलरी • घड़ियां",
      "industries.beauty": "ब्यूटी और स्किनकेयर",
      "industries.beautyDesc": "कॉस्मेटिक्स • स्किनकेयर • वेलनेस • स्पा",
      "industries.designer": "डिजाइनर फैशन",
      "industries.designerDesc": "हाउट कॉउचर • ब्राइडल • लग्जरी अपैरल",
      "industries.footer": "अपना उद्योग नहीं दिख रहा?",
      "industries.footerHighlight": "हम दुनिया भर में किसी भी व्यवसाय के लिए विज्ञापन बनाते हैं।",
      // ROI Section
      "roi.badge": "गणित समझ में आता है",
      "roi.title": "अपने निवेश को बदलें",
      "roi.titleHighlight": "बड़े ROI में",
      "roi.subtitle": "स्मार्ट व्यवसाय मालिक समझते हैं: बेहतर क्रिएटिव = बेहतर प्रदर्शन = अधिक लाभ। यहां बताया गया है कि edgeaihub आपके रिटर्न को कैसे बढ़ाता है।",
      "roi.subtitleBold": "बेहतर क्रिएटिव = बेहतर प्रदर्शन = अधिक लाभ",
      "roi.step1.title": "स्मार्ट निवेश",
      "roi.step1.description": "न्यूनतम लागत पर प्रीमियम वीडियो विज्ञापन बनाएं — कई क्रिएटिव का तेजी से परीक्षण करें।",
      "roi.step2.title": "बेहतर क्रिएटिव",
      "roi.step2.description": "AI-अनुकूलित विजुअल और हुक जो पहले 3 सेकंड में ध्यान आकर्षित करते हैं।",
      "roi.step3.title": "उच्च CTR",
      "roi.step3.description": "गुणवत्ता क्रिएटिव = हर विज्ञापन प्लेटफॉर्म पर उच्च क्लिक-थ्रू दरें।",
      "roi.step4.title": "कम विज्ञापन लागत",
      "roi.step4.description": "बेहतर प्रदर्शन = कम CPC = प्रति रुपये अधिक रूपांतरण।",
      "roi.result.title": "परिणाम:",
      "roi.result.highlight": "10x - 100x निवेश पर रिटर्न",
      "roi.result.description": "edgeaihub का उपयोग करने वाले व्यवसाय 50-70% कम अधिग्रहण लागत और पारंपरिक वीडियो उत्पादन की तुलना में 3x अधिक सहभागिता दरों की रिपोर्ट करते हैं।",
      "roi.result.lowerCost": "50-70% कम अधिग्रहण लागत",
      "roi.result.engagement": "3x अधिक सहभागिता दरें",
      "roi.investment": "किफायती",
      "roi.investmentLabel": "आपका निवेश",
      "roi.returns": "10x-100x",
      "roi.returnsLabel": "संभावित रिटर्न",
      "common.call": "कॉल",
      "common.email": "ईमेल",
    },
    kn: {
      ...baseTranslations,
      "nav.whyUs": "ನಮ್ಮನ್ನು ಏಕೆ",
      "nav.samples": "ಮಾದರಿಗಳು",
      "nav.aiShortFilms": "AI ಶಾರ್ಟ್ ಫಿಲ್ಮ್ಸ್",
      "nav.howItWorks": "ಹೇಗೆ ಕಾರ್ಯನಿರ್ವಹಿಸುತ್ತದೆ",
      "nav.blog": "ಬ್ಲಾಗ್",
      "hero.badge.aiPowered": "AI-ಚಾಲಿತ",
      "hero.badge.conversionFocused": "ಪರಿವರ್ತನೆ-ಕೇಂದ್ರಿತ",
      "hero.badge.globalQuality": "ಜಾಗತಿಕ ಗುಣಮಟ್ಟ",
      "hero.badge.fastDelivery": "ವೇಗದ ವಿತರಣೆ",
      "hero.title1": "ಪ್ರೀಮಿಯಂ AI ವೀಡಿಯೊ ಜಾಹೀರಾತುಗಳು",
      "hero.title2": "ನಿಮ್ಮ ವ್ಯಾಪಾರಕ್ಕಾಗಿ",
      "hero.subtitle": "ಏಜೆನ್ಸಿಗಳಿಗೆ ಲಕ್ಷಗಳನ್ನು ವ್ಯರ್ಥ ಮಾಡುವುದನ್ನು ನಿಲ್ಲಿಸಿ। AI ನಿಂದ ಚಾಲಿತ ಸ್ಟುಡಿಯೋ-ಗುಣಮಟ್ಟದ 30-ಸೆಕೆಂಡ್ ವೀಡಿಯೊ ಜಾಹೀರಾತುಗಳನ್ನು ಪಡೆಯಿರಿ — ವೇಗವಾಗಿ, ಸ್ಮಾರ್ಟ್ ಆಗಿ ಮತ್ತು ಕಡಿಮೆ ವೆಚ್ಚದಲ್ಲಿ।",
      "hero.trust": "ಭಾರತ ಮತ್ತು ವಿಶ್ವಾದ್ಯಂತ 10,000+ ವ್ಯಾಪಾರಗಳಿಂದ ವಿಶ್ವಾಸಾರ್ಹ",
      "hero.emailBtn": "ಇಮೇಲ್ ಮೂಲಕ ಸಂಪರ್ಕಿಸಿ",
      "hero.callBtn": "ಕರೆ ಮಾಡಿ",
      "hero.stats.adsCreated": "ಜಾಹೀರಾತುಗಳು ರಚಿಸಲಾಗಿದೆ",
      "hero.stats.fastDelivery": "ವೇಗದ ವಿತರಣೆ",
      "hero.stats.countries": "ದೇಶಗಳಿಗೆ ಸೇವೆ",
      "hero.stats.satisfaction": "ತೃಪ್ತಿ",
      "cta.badge": "ವೀಡಿಯೊ ಜಾಹೀರಾತಿನ ಭವಿಷ್ಯ",
      "cta.title1": "ನಿಮ್ಮ ಪ್ರತಿಸ್ಪರ್ಧಿಗಳು ಈಗಾಗಲೇ",
      "cta.title2": "AI ಜಾಹೀರಾತುಗಳನ್ನು ಬಳಸುತ್ತಿದ್ದಾರೆ",
      "cta.subtitle": "ನೀವು ಕಾಯುವ ಪ್ರತಿ ದಿನ, ನೀವು ಉತ್ತಮ ವೀಡಿಯೊ ವಿಷಯವಿರುವ ವ್ಯಾಪಾರಗಳಿಗೆ ಗ್ರಾಹಕರನ್ನು ಕಳೆದುಕೊಳ್ಳುತ್ತೀರಿ。",
      "cta.contact": "ಪ್ರೀಮಿಯಂ AI ವೀಡಿಯೊ ಜಾಹೀರಾತುಗಳಿಗಾಗಿ ಇಂದೇ ಸಂಪರ್ಕಿಸಿ。",
      "cta.whyChoose": "edgeaihub ಅನ್ನು ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು?",
      "cta.point1": "ಏಜೆನ್ಸಿಗಳು ಲಕ್ಷಗಳನ್ನು ವಿಧಿಸುತ್ತವೆ — ನಾವು ಕೈಗೆಟುಕುವ ಬೆಲೆಯಲ್ಲಿದ್ದೇವೆ",
      "cta.point2": "ವಾರಗಳ ಕಾಯುವಿಕೆ — ನಾವು 24 ಗಂಟೆಗಳಲ್ಲಿ ತಲುಪಿಸುತ್ತೇವೆ",
      "cta.point3": "ಅಸಮಂಜಸ ಗುಣಮಟ್ಟ — ನಾವು ಪ್ರೀಮಿಯಂ ಔಟ್ಪುಟ್ ಖಾತರಿ ನೀಡುತ್ತೇವೆ",
      "cta.point4": "ಸಂಕೀರ್ಣ ಪ್ರಕ್ರಿಯೆಗಳು — ನಾವು ಅದನ್ನು ಸುಲಭಗೊಳಿಸುತ್ತೇವೆ",
      "cta.noCommitments": "ಯಾವುದೇ ಬದ್ಧತೆಗಳಿಲ್ಲ. ಮಾತುಕತೆ ಪ್ರಾರಂಭಿಸಿ।",
      "whyUs.badge": "ಸ್ಮಾರ್ಟ್ ಆಯ್ಕೆ",
      "whyUs.title": "ಏಕೆ",
      "whyUs.subtitle": "ಏಜೆನ್ಸಿಗಳು ಲಕ್ಷಗಳನ್ನು ವಿಧಿಸುತ್ತವೆ. ಫ್ರೀಲ್ಯಾನ್ಸರ್‌ಗಳು ನಿರಾಶೆಗೊಳಿಸುತ್ತಾರೆ. ಸಾಮಾನ್ಯ ಉಪಕರಣಗಳು ವಿಫಲವಾಗುತ್ತವೆ. ನಾವು ಕೈಗೆಟುಕುವ ಬೆಲೆಗಳಲ್ಲಿ ಪ್ರೀಮಿಯಂ ಗುಣಮಟ್ಟವನ್ನು ನೀಡುತ್ತೇವೆ।",
      "whyUs.agencies.title": "ಸಾಂಪ್ರದಾಯಿಕ ಏಜೆನ್ಸಿಗಳು",
      "whyUs.agencies.point1": "ಪ್ರತಿ ವೀಡಿಯೊಗೆ ₹50,000 - ₹5,00,000",
      "whyUs.agencies.point2": "2-4 ವಾರಗಳ ವಿತರಣಾ ಸಮಯ",
      "whyUs.agencies.point3": "ಅಂತ್ಯವಿಲ್ಲದ ಪರಿಷ್ಕರಣೆ ಚಕ್ರಗಳು",
      "whyUs.agencies.point4": "ಸಂಕೀರ್ಣ ಒಪ್ಪಂದಗಳು ಮತ್ತು ಬದ್ಧತೆಗಳು",
      "whyUs.freelancers.title": "ಫ್ರೀಲ್ಯಾನ್ಸರ್‌ಗಳು",
      "whyUs.freelancers.point1": "ಅಸಮಂಜಸ ಗುಣಮಟ್ಟ",
      "whyUs.freelancers.point2": "ಅವಿಶ್ವಾಸಾರ್ಹ ಸಮಯಸೀಮೆಗಳು",
      "whyUs.freelancers.point3": "ಸೀಮಿತ ಸೃಜನಶೀಲ ಆಯ್ಕೆಗಳು",
      "whyUs.freelancers.point4": "ಯಾವುದೇ ಸ್ಕೇಲೆಬಿಲಿಟಿ ಇಲ್ಲ",
      "whyUs.genericAI.title": "ಸಾಮಾನ್ಯ AI ಉಪಕರಣಗಳು",
      "whyUs.genericAI.point1": "ಟೆಂಪ್ಲೇಟ್ ತರಹದ ಔಟ್ಪುಟ್",
      "whyUs.genericAI.point2": "ಯಾವುದೇ ಜಾಹೀರಾತು ಆಪ್ಟಿಮೈಸೇಶನ್ ಇಲ್ಲ",
      "whyUs.genericAI.point3": "ಸಂಕೀರ್ಣ ಕಲಿಕೆಯ ವಕ್ರರೇಖೆ",
      "whyUs.genericAI.point4": "ಕಳಪೆ ಪರಿವರ್ತನೆ ದರಗಳು",
      "whyUs.edgeaihub.point1": "ಕೈಗೆಟುಕುವ ಪ್ರೀಮಿಯಂ ವೀಡಿಯೊ ಜಾಹೀರಾತುಗಳು",
      "whyUs.edgeaihub.point2": "24-ಗಂಟೆ ವಿತರಣೆ ಖಾತರಿ",
      "whyUs.edgeaihub.point3": "ಪರಿವರ್ತನೆ-ಆಪ್ಟಿಮೈಸ್ಡ್ ಟೆಂಪ್ಲೇಟ್‌ಗಳು",
      "whyUs.edgeaihub.point4": "ತಕ್ಷಣ ಅನಿಯಮಿತ ಜಾಹೀರಾತುಗಳನ್ನು ಸ್ಕೇಲ್ ಮಾಡಿ",
      "trust.badge": "ನಿಮ್ಮ ನಂಬಿಕೆ ಮುಖ್ಯ",
      "trust.title": "ಗುಣಮಟ್ಟ ಮತ್ತು",
      "trust.titleHighlight": "ವಿಶ್ವಾಸಾರ್ಹತೆ",
      "trust.subtitle": "ನಾವು ನಿಮ್ಮ ಬ್ರ್ಯಾಂಡ್ ಅನ್ನು ಗಂಭೀರವಾಗಿ ತೆಗೆದುಕೊಳ್ಳುತ್ತೇವೆ. ಪ್ರತಿ ಜಾಹೀರಾತು ಕಠಿಣ ಪರಿಶೀಲನೆಯ ಮೂಲಕ ಹೋಗುತ್ತದೆ।",
      "footer.tagline": "ಪ್ರೀಮಿಯಂ AI ವೀಡಿಯೊ ಜಾಹೀರಾತುಗಳು",
      "footer.description": "ಜಾಗತಿಕ ಬ್ರ್ಯಾಂಡ್‌ಗಳಿಗೆ ಪ್ರೀಮಿಯಂ AI ವೀಡಿಯೊ ಜಾಹೀರಾತುಗಳು + ಹಾಲಿವುಡ್-ಗುಣಮಟ್ಟದ AI ಶಾರ್ಟ್ ಫಿಲ್ಮ್ಸ್。",
      "footer.ourServices": "ನಮ್ಮ ಸೇವೆಗಳು",
      "footer.services.videoAds": "AI ವೀಡಿಯೊ ಜಾಹೀರಾತುಗಳು",
      "footer.services.shortFilms": "AI ಶಾರ್ಟ್ ಫಿಲ್ಮ್ಸ್",
      "footer.services.brandVideos": "ಬ್ರ್ಯಾಂಡ್ ವೀಡಿಯೊಗಳು",
      "footer.services.productAds": "ಉತ್ಪನ್ನ ಜಾಹೀರಾತುಗಳು",
      "footer.industriesWeServe": "ನಾವು ಸೇವೆ ಮಾಡುವ ಉದ್ಯಮಗಳು",
      "footer.industries.fashion": "ಫ್ಯಾಷನ್ ಮತ್ತು ಆಭರಣಗಳು",
      "footer.industries.ecommerce": "ಇ-ಕಾಮರ್ಸ್",
      "footer.industries.realestate": "ರಿಯಲ್ ಎಸ್ಟೇಟ್",
      "footer.industries.education": "ಶಿಕ್ಷಣ",
      "footer.industries.restaurants": "ರೆಸ್ಟೋರೆಂಟ್‌ಗಳು",
      "footer.industries.healthcare": "ಆರೋಗ್ಯ ಸೇವೆ",
      "footer.getInTouch": "ಸಂಪರ್ಕಿಸಿ",
      "footer.businessHours": "ಸೋಮ-ಶನಿ, ಬೆಳಿಗ್ಗೆ 9 - ರಾತ್ರಿ 8 IST",
      "footer.office": "ಕಚೇರಿ",
      "footer.rights": "ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ।",
      "footer.aiPowered": "AI-ಚಾಲಿತ",
      "footer.cinemaQuality": "ಸಿನಿಮಾ ಗುಣಮಟ್ಟ",
      "footer.globalService": "ಜಾಗತಿಕ ಸೇವೆ",
      "blog.badge": "ಜ್ಞಾನ ಕೇಂದ್ರ",
      "blog.title": "AI ವೀಡಿಯೊ ಮಾರ್ಕೆಟಿಂಗ್",
      "blog.titleHighlight": "ಬ್ಲಾಗ್",
      "blog.subtitle": "ವೈರಲ್ ವೀಡಿಯೊ ಜಾಹೀರಾತುಗಳನ್ನು ರಚಿಸಲು ಮತ್ತು ನಿಮ್ಮ ವ್ಯಾಪಾರವನ್ನು ಬೆಳೆಸಲು ತಜ್ಞ ಸಲಹೆಗಳು, ತಂತ್ರಗಳು ಮತ್ತು ಮಾರ್ಗದರ್ಶಿಗಳು",
      "blog.readArticle": "ಲೇಖನ ಓದಿ",
      "blog.backToBlog": "ಬ್ಲಾಗ್‌ಗೆ ಹಿಂತಿರುಗಿ",
      "blog.relatedArticles": "ಸಂಬಂಧಿತ ಲೇಖನಗಳು",
      "blog.ctaTitle": "ನಿಮ್ಮ ಸ್ವಂತ AI ವೀಡಿಯೊ ಜಾಹೀರಾತು ರಚಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಾ?",
      "blog.ctaSubtitle": "24-ಗಂಟೆ ವಿತರಣೆಯೊಂದಿಗೆ ಪ್ರೀಮಿಯಂ AI ವೀಡಿಯೊ ಜಾಹೀರಾತು ಪಡೆಯಿರಿ",
      "blog.category.aiMarketing": "AI ಮಾರ್ಕೆಟಿಂಗ್",
      "blog.category.socialMedia": "ಸೋಶಿಯಲ್ ಮೀಡಿಯಾ",
      "blog.category.aiFilms": "AI ಫಿಲ್ಮ್ಸ್",
      "blog.category.realEstate": "ರಿಯಲ್ ಎಸ್ಟೇಟ್",
      "blog.category.ecommerce": "ಇ-ಕಾಮರ್ಸ್",
      "blog.category.luxury": "ಲಕ್ಸುರಿ",
      "blog.minRead": "ನಿಮಿಷ ಓದು",
      "blog.share": "ಹಂಚಿಕೊಳ್ಳಿ",
      "common.call": "ಕರೆ",
      "common.email": "ಇಮೇಲ್",
    },
    te: {
      ...baseTranslations,
      "nav.whyUs": "మేమే ఎందుకు",
      "nav.samples": "నమూనాలు",
      "nav.aiShortFilms": "AI షార్ట్ ఫిల్మ్స్",
      "nav.howItWorks": "ఎలా పని చేస్తుంది",
      "nav.blog": "బ్లాగ్",
      "hero.badge.aiPowered": "AI-ఆధారిత",
      "hero.badge.conversionFocused": "మార్పిడి-కేంద్రీకృత",
      "hero.badge.globalQuality": "గ్లోబల్ నాణ్యత",
      "hero.badge.fastDelivery": "వేగవంతమైన డెలివరీ",
      "hero.title1": "ప్రీమియం AI వీడియో యాడ్స్",
      "hero.title2": "మీ వ్యాపారం కోసం",
      "hero.subtitle": "ఏజెన్సీలకు లక్షలు వృధా చేయడం ఆపండి। AI ద్వారా నడిచే స్టూడియో-నాణ్యత 30-సెకన్ల వీడియో యాడ్స్ పొందండి — వేగంగా, తెలివిగా మరియు తక్కువ ఖర్చుతో।",
      "hero.trust": "భారతదేశం మరియు ప్రపంచవ్యాప్తంగా 10,000+ వ్యాపారాలు విశ్వసిస్తాయి",
      "hero.emailBtn": "ఇమెయిల్ ద్వారా సంప్రదించండి",
      "hero.callBtn": "కాల్ చేయండి",
      "hero.stats.adsCreated": "యాడ్స్ సృష్టించబడ్డాయి",
      "hero.stats.fastDelivery": "వేగవంతమైన డెలివరీ",
      "hero.stats.countries": "దేశాలకు సేవలు",
      "hero.stats.satisfaction": "సంతృప్తి",
      "cta.badge": "వీడియో అడ్వర్టైజింగ్ భవిష్యత్తు",
      "cta.title1": "మీ పోటీదారులు ఇప్పటికే",
      "cta.title2": "AI యాడ్స్ ఉపయోగిస్తున్నారు",
      "cta.subtitle": "మీరు వేచి ఉన్న ప్రతి రోజు, మెరుగైన వీడియో కంటెంట్ ఉన్న వ్యాపారాలకు కస్టమర్లను కోల్పోతారు.",
      "cta.contact": "ప్రీమియం AI వీడియో యాడ్స్ కోసం ఈరోజే సంప్రదించండి.",
      "cta.whyChoose": "edgeaihub ఎందుకు ఎంచుకోవాలి?",
      "cta.point1": "ఏజెన్సీలు లక్షలు వసూలు చేస్తాయి — మేము సరసమైన ధరలో అందిస్తాము",
      "cta.point2": "వారాల నిరీక్షణ — మేము 24 గంటల్లో డెలివర్ చేస్తాము",
      "cta.point3": "అస్థిర నాణ్యత — మేము ప్రీమియం అవుట్‌పుట్ హామీ ఇస్తాము",
      "cta.point4": "సంక్లిష్ట ప్రక్రియలు — మేము దాన్ని సులభం చేస్తాము",
      "cta.noCommitments": "కమిట్‌మెంట్లు లేవు. సంభాషణ ప్రారంభించండి.",
      "whyUs.badge": "తెలివైన ఎంపిక",
      "whyUs.title": "ఎందుకు",
      "whyUs.subtitle": "ఏజెన్సీలు లక్షలు వసూలు చేస్తాయి. ఫ్రీలాన్సర్లు నిరాశపరుస్తారు. సాధారణ సాధనాలు విఫలమవుతాయి. మేము సరసమైన ధరలలో ప్రీమియం నాణ్యతను అందిస్తాము.",
      "whyUs.agencies.title": "సాంప్రదాయ ఏజెన్సీలు",
      "whyUs.agencies.point1": "ప్రతి వీడియోకు ₹50,000 - ₹5,00,000",
      "whyUs.agencies.point2": "2-4 వారాల డెలివరీ సమయం",
      "whyUs.agencies.point3": "అంతులేని సవరణ చక్రాలు",
      "whyUs.agencies.point4": "సంక్లిష్ట ఒప్పందాలు & కట్టుబాట్లు",
      "whyUs.freelancers.title": "ఫ్రీలాన్సర్లు",
      "whyUs.freelancers.point1": "అస్థిర నాణ్యత",
      "whyUs.freelancers.point2": "నమ్మదగని టైమ్‌లైన్లు",
      "whyUs.freelancers.point3": "పరిమిత సృజనాత్మక ఎంపికలు",
      "whyUs.freelancers.point4": "స్కేలబిలిటీ లేదు",
      "whyUs.genericAI.title": "సాధారణ AI సాధనాలు",
      "whyUs.genericAI.point1": "టెంప్లేట్-వంటి అవుట్‌పుట్",
      "whyUs.genericAI.point2": "యాడ్ ఆప్టిమైజేషన్ లేదు",
      "whyUs.genericAI.point3": "సంక్లిష్ట నేర్చుకునే వక్రత",
      "whyUs.genericAI.point4": "తక్కువ మార్పిడి రేట్లు",
      "whyUs.edgeaihub.point1": "సరసమైన ప్రీమియం వీడియో యాడ్స్",
      "whyUs.edgeaihub.point2": "24-గంటల డెలివరీ హామీ",
      "whyUs.edgeaihub.point3": "మార్పిడి-ఆప్టిమైజ్డ్ టెంప్లేట్లు",
      "whyUs.edgeaihub.point4": "వెంటనే అపరిమిత యాడ్స్ స్కేల్ చేయండి",
      "trust.badge": "మీ నమ్మకం ముఖ్యం",
      "trust.title": "నాణ్యత &",
      "trust.titleHighlight": "విశ్వసనీయత",
      "trust.subtitle": "మేము మీ బ్రాండ్‌ను తీవ్రంగా తీసుకుంటాము. ప్రతి యాడ్ కఠినమైన తనిఖీల ద్వారా వెళుతుంది.",
      "footer.tagline": "ప్రీమియం AI వీడియో యాడ్స్",
      "footer.description": "గ్లోబల్ బ్రాండ్‌లకు ప్రీమియం AI వీడియో యాడ్స్ + హాలీవుడ్-నాణ్యత AI షార్ట్ ఫిల్మ్స్.",
      "footer.ourServices": "మా సేవలు",
      "footer.services.videoAds": "AI వీడియో యాడ్స్",
      "footer.services.shortFilms": "AI షార్ట్ ఫిల్మ్స్",
      "footer.services.brandVideos": "బ్రాండ్ వీడియోలు",
      "footer.services.productAds": "ఉత్పత్తి యాడ్స్",
      "footer.industriesWeServe": "మేము సేవ చేసే పరిశ్రమలు",
      "footer.industries.fashion": "ఫ్యాషన్ & జ్యువెలరీ",
      "footer.industries.ecommerce": "ఈ-కామర్స్",
      "footer.industries.realestate": "రియల్ ఎస్టేట్",
      "footer.industries.education": "విద్య",
      "footer.industries.restaurants": "రెస్టారెంట్లు",
      "footer.industries.healthcare": "ఆరోగ్య సంరక్షణ",
      "footer.getInTouch": "సంప్రదించండి",
      "footer.businessHours": "సోమ-శని, ఉ 9 - రా 8 IST",
      "footer.office": "కార్యాలయం",
      "footer.rights": "అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.",
      "footer.aiPowered": "AI-ఆధారిత",
      "footer.cinemaQuality": "సినిమా నాణ్యత",
      "footer.globalService": "గ్లోబల్ సర్వీస్",
      "blog.badge": "జ్ఞాన కేంద్రం",
      "blog.title": "AI వీడియో మార్కెటింగ్",
      "blog.titleHighlight": "బ్లాగ్",
      "blog.subtitle": "వైరల్ వీడియో యాడ్స్ సృష్టించడానికి మరియు మీ వ్యాపారాన్ని పెంచుకోవడానికి నిపుణుల చిట్కాలు, వ్యూహాలు మరియు గైడ్లు",
      "blog.readArticle": "ఆర్టికల్ చదవండి",
      "blog.backToBlog": "బ్లాగ్‌కు తిరిగి",
      "blog.relatedArticles": "సంబంధిత ఆర్టికల్స్",
      "blog.ctaTitle": "మీ స్వంత AI వీడియో యాడ్ సృష్టించడానికి సిద్ధంగా ఉన్నారా?",
      "blog.ctaSubtitle": "24-గంటల డెలివరీతో ప్రీమియం AI వీడియో యాడ్ పొందండి",
      "blog.category.aiMarketing": "AI మార్కెటింగ్",
      "blog.category.socialMedia": "సోషల్ మీడియా",
      "blog.category.aiFilms": "AI ఫిల్మ్స్",
      "blog.category.realEstate": "రియల్ ఎస్టేట్",
      "blog.category.ecommerce": "ఈ-కామర్స్",
      "blog.category.luxury": "లగ్జరీ",
      "blog.minRead": "నిమిషాలు చదవండి",
      "blog.share": "షేర్ చేయండి",
      "common.call": "కాల్",
      "common.email": "ఇమెయిల్",
    },
    ta: {
      ...baseTranslations,
      "nav.whyUs": "ஏன் நாம்",
      "nav.samples": "மாதிரிகள்",
      "nav.aiShortFilms": "AI குறும்படங்கள்",
      "nav.howItWorks": "எப்படி வேலை செய்கிறது",
      "nav.blog": "வலைப்பதிவு",
      "hero.badge.aiPowered": "AI-இயக்கப்படும்",
      "hero.badge.conversionFocused": "மாற்றம்-மையம்",
      "hero.badge.globalQuality": "உலகளாவிய தரம்",
      "hero.badge.fastDelivery": "விரைவான விநியோகம்",
      "hero.title1": "பிரீமியம் AI வீடியோ விளம்பரங்கள்",
      "hero.title2": "உங்கள் வணிகத்திற்காக",
      "hero.subtitle": "ஏஜென்சிகளுக்கு லட்சங்களை வீணடிப்பதை நிறுத்துங்கள். AI மூலம் இயக்கப்படும் ஸ்டுடியோ-தர 30-வினாடி வீடியோ விளம்பரங்களைப் பெறுங்கள் — விரைவாக, புத்திசாலித்தனமாக மற்றும் குறைந்த செலவில்.",
      "hero.trust": "இந்தியா மற்றும் உலகம் முழுவதும் 10,000+ வணிகங்கள் நம்புகின்றன",
      "hero.emailBtn": "மின்னஞ்சல் வழியாக தொடர்பு கொள்ளுங்கள்",
      "hero.callBtn": "அழைக்கவும்",
      "hero.stats.adsCreated": "விளம்பரங்கள் உருவாக்கப்பட்டன",
      "hero.stats.fastDelivery": "விரைவான விநியோகம்",
      "hero.stats.countries": "நாடுகளுக்கு சேவை",
      "hero.stats.satisfaction": "திருப்தி",
      "cta.badge": "வீடியோ விளம்பரத்தின் எதிர்காலம்",
      "cta.title1": "உங்கள் போட்டியாளர்கள் ஏற்கனவே",
      "cta.title2": "AI விளம்பரங்களைப் பயன்படுத்துகிறார்கள்",
      "cta.subtitle": "நீங்கள் காத்திருக்கும் ஒவ்வொரு நாளும், சிறந்த வீடியோ உள்ளடக்கம் கொண்ட வணிகங்களுக்கு வாடிக்கையாளர்களை இழக்கிறீர்கள்.",
      "cta.contact": "பிரீமியம் AI வீடியோ விளம்பரங்களுக்கு இன்றே தொடர்பு கொள்ளுங்கள்.",
      "cta.whyChoose": "edgeaihub ஏன் தேர்வு செய்ய வேண்டும்?",
      "cta.point1": "ஏஜென்சிகள் லட்சங்கள் வசூலிக்கின்றன — நாங்கள் மலிவானவர்கள்",
      "cta.point2": "வாரங்கள் காத்திருப்பு — நாங்கள் 24 மணி நேரத்தில் வழங்குகிறோம்",
      "cta.point3": "சீரற்ற தரம் — நாங்கள் பிரீமியம் வெளியீட்டை உத்தரவாதம் செய்கிறோம்",
      "cta.point4": "சிக்கலான செயல்முறைகள் — நாங்கள் அதை எளிதாக்குகிறோம்",
      "cta.noCommitments": "உறுதிமொழிகள் இல்லை. உரையாடலைத் தொடங்குங்கள்.",
      "whyUs.badge": "புத்திசாலித்தனமான தேர்வு",
      "whyUs.title": "ஏன்",
      "whyUs.subtitle": "ஏஜென்சிகள் லட்சங்கள் வசூலிக்கின்றன. ஃப்ரீலான்சர்கள் ஏமாற்றுகின்றனர். பொதுவான கருவிகள் தோல்வியடைகின்றன. மலிவான விலையில் பிரீமியம் தரத்தை வழங்குகிறோம்.",
      "whyUs.agencies.title": "பாரம்பரிய ஏஜென்சிகள்",
      "whyUs.agencies.point1": "ஒரு வீடியோவுக்கு ₹50,000 - ₹5,00,000",
      "whyUs.agencies.point2": "2-4 வாரங்கள் விநியோக நேரம்",
      "whyUs.agencies.point3": "முடிவில்லாத திருத்த சுழற்சிகள்",
      "whyUs.agencies.point4": "சிக்கலான ஒப்பந்தங்கள் & உறுதிமொழிகள்",
      "whyUs.freelancers.title": "ஃப்ரீலான்சர்கள்",
      "whyUs.freelancers.point1": "சீரற்ற தரம்",
      "whyUs.freelancers.point2": "நம்பகத்தன்மையற்ற காலக்கெடுக்கள்",
      "whyUs.freelancers.point3": "குறைந்த ஆக்கபூர்வ விருப்பங்கள்",
      "whyUs.freelancers.point4": "அளவிடுதல் இல்லை",
      "whyUs.genericAI.title": "பொதுவான AI கருவிகள்",
      "whyUs.genericAI.point1": "டெம்ப்ளேட்-போன்ற வெளியீடு",
      "whyUs.genericAI.point2": "விளம்பர தேர்வுமுறை இல்லை",
      "whyUs.genericAI.point3": "சிக்கலான கற்றல் வளைவு",
      "whyUs.genericAI.point4": "மோசமான மாற்ற விகிதங்கள்",
      "whyUs.edgeaihub.point1": "மலிவான பிரீமியம் வீடியோ விளம்பரங்கள்",
      "whyUs.edgeaihub.point2": "24-மணி நேர விநியோக உத்தரவாதம்",
      "whyUs.edgeaihub.point3": "மாற்றம்-தேர்வுமுறை செய்யப்பட்ட டெம்ப்ளேட்கள்",
      "whyUs.edgeaihub.point4": "உடனடியாக வரம்பற்ற விளம்பரங்களை அளவிடுங்கள்",
      "trust.badge": "உங்கள் நம்பிக்கை முக்கியம்",
      "trust.title": "தரம் &",
      "trust.titleHighlight": "நம்பகத்தன்மை",
      "trust.subtitle": "உங்கள் பிராண்டை தீவிரமாக எடுத்துக்கொள்கிறோம். ஒவ்வொரு விளம்பரமும் கடுமையான சோதனைகளுக்கு உட்படுகிறது.",
      "footer.tagline": "பிரீமியம் AI வீடியோ விளம்பரங்கள்",
      "footer.description": "உலகளாவிய பிராண்டுகளுக்கு பிரீமியம் AI வீடியோ விளம்பரங்கள் + ஹாலிவுட்-தர AI குறும்படங்கள்.",
      "footer.ourServices": "எங்கள் சேவைகள்",
      "footer.services.videoAds": "AI வீடியோ விளம்பரங்கள்",
      "footer.services.shortFilms": "AI குறும்படங்கள்",
      "footer.services.brandVideos": "பிராண்ட் வீடியோக்கள்",
      "footer.services.productAds": "தயாரிப்பு விளம்பரங்கள்",
      "footer.industriesWeServe": "நாங்கள் சேவை செய்யும் தொழில்கள்",
      "footer.industries.fashion": "ஃபேஷன் & நகைகள்",
      "footer.industries.ecommerce": "ஈ-காமர்ஸ்",
      "footer.industries.realestate": "ரியல் எஸ்டேட்",
      "footer.industries.education": "கல்வி",
      "footer.industries.restaurants": "உணவகங்கள்",
      "footer.industries.healthcare": "சுகாதார சேவை",
      "footer.getInTouch": "தொடர்பு கொள்ளுங்கள்",
      "footer.businessHours": "திங்-சனி, கா 9 - இர 8 IST",
      "footer.office": "அலுவலகம்",
      "footer.rights": "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
      "footer.aiPowered": "AI-இயக்கப்படும்",
      "footer.cinemaQuality": "சினிமா தரம்",
      "footer.globalService": "உலகளாவிய சேவை",
      "blog.badge": "அறிவு மையம்",
      "blog.title": "AI வீடியோ சந்தைப்படுத்தல்",
      "blog.titleHighlight": "வலைப்பதிவு",
      "blog.subtitle": "வைரல் வீடியோ விளம்பரங்களை உருவாக்கவும் உங்கள் வணிகத்தை வளர்க்கவும் நிபுணர் குறிப்புகள், உத்திகள் மற்றும் வழிகாட்டிகள்",
      "blog.readArticle": "கட்டுரையைப் படிக்கவும்",
      "blog.backToBlog": "வலைப்பதிவுக்குத் திரும்பு",
      "blog.relatedArticles": "தொடர்புடைய கட்டுரைகள்",
      "blog.ctaTitle": "உங்கள் சொந்த AI வீடியோ விளம்பரத்தை உருவாக்க தயாரா?",
      "blog.ctaSubtitle": "24-மணி நேர விநியோகத்துடன் பிரீமியம் AI வீடியோ விளம்பரத்தைப் பெறுங்கள்",
      "blog.category.aiMarketing": "AI சந்தைப்படுத்தல்",
      "blog.category.socialMedia": "சமூக ஊடகம்",
      "blog.category.aiFilms": "AI படங்கள்",
      "blog.category.realEstate": "ரியல் எஸ்டேட்",
      "blog.category.ecommerce": "ஈ-காமர்ஸ்",
      "blog.category.luxury": "ஆடம்பரம்",
      "blog.minRead": "நிமிட வாசிப்பு",
      "blog.share": "பகிர்",
      "common.call": "அழைப்பு",
      "common.email": "மின்னஞ்சல்",
    },
    ml: {
      ...baseTranslations,
      "nav.whyUs": "എന്തുകൊണ്ട് ഞങ്ങൾ",
      "nav.samples": "സാമ്പിളുകൾ",
      "nav.aiShortFilms": "AI ഷോർട്ട് ഫിലിമുകൾ",
      "nav.howItWorks": "എങ്ങനെ പ്രവർത്തിക്കുന്നു",
      "nav.blog": "ബ്ലോഗ്",
      "hero.title1": "പ്രീമിയം AI വീഡിയോ പരസ്യങ്ങൾ",
      "hero.title2": "നിങ്ങളുടെ ബിസിനസിനായി",
      "hero.subtitle": "ഏജൻസികൾക്ക് ലക്ഷങ്ങൾ പാഴാക്കുന്നത് നിർത്തുക. AI ഉപയോഗിച്ച് പ്രവർത്തിക്കുന്ന സ്റ്റുഡിയോ-നിലവാരമുള്ള വീഡിയോ പരസ്യങ്ങൾ നേടുക.",
      "hero.trust": "ഇന്ത്യയിലും ലോകമെമ്പാടും 10,000+ ബിസിനസുകൾ വിശ്വസിക്കുന്നു",
      "footer.tagline": "പ്രീമിയം AI വീഡിയോ പരസ്യങ്ങൾ",
      "footer.ourServices": "ഞങ്ങളുടെ സേവനങ്ങൾ",
      "footer.industriesWeServe": "ഞങ്ങൾ സേവിക്കുന്ന വ്യവസായങ്ങൾ",
      "footer.getInTouch": "ബന്ധപ്പെടുക",
      "footer.office": "ഓഫീസ്",
      "common.call": "വിളിക്കുക",
      "common.email": "ഇമെയിൽ",
    },
    mr: {
      ...baseTranslations,
      "nav.whyUs": "आम्हाला का",
      "nav.samples": "नमुने",
      "nav.aiShortFilms": "AI शॉर्ट फिल्म्स",
      "nav.howItWorks": "कसे काम करते",
      "nav.blog": "ब्लॉग",
      "hero.title1": "प्रीमियम AI व्हिडिओ जाहिराती",
      "hero.title2": "तुमच्या व्यवसायासाठी",
      "hero.subtitle": "एजन्सींवर लाखो खर्च करणे थांबवा। AI द्वारे चालित स्टुडिओ-गुणवत्तेच्या व्हिडिओ जाहिराती मिळवा.",
      "hero.trust": "भारत आणि जगभरातील 10,000+ व्यवसायांचा विश्वास",
      "footer.tagline": "प्रीमियम AI व्हिडिओ जाहिराती",
      "footer.ourServices": "आमच्या सेवा",
      "footer.industriesWeServe": "आम्ही सेवा देतो त्या उद्योग",
      "footer.getInTouch": "संपर्क साधा",
      "footer.office": "कार्यालय",
      "common.call": "कॉल",
      "common.email": "ईमेल",
    },
    gu: {
      ...baseTranslations,
      "nav.whyUs": "અમને કેમ",
      "nav.samples": "નમૂનાઓ",
      "nav.aiShortFilms": "AI શોર્ટ ફિલ્મ્સ",
      "nav.howItWorks": "કેવી રીતે કામ કરે છે",
      "nav.blog": "બ્લોગ",
      "hero.title1": "પ્રીમિયમ AI વિડિયો જાહેરાતો",
      "hero.title2": "તમારા વ્યવસાય માટે",
      "hero.subtitle": "એજન્સીઓ પર લાખો બગાડવાનું બંધ કરો। AI દ્વારા સંચાલિત સ્ટુડિયો-ગુણવત્તાના વિડિયો જાહેરાતો મેળવો.",
      "hero.trust": "ભારત અને વિશ્વભરમાં 10,000+ વ્યવસાયો દ્વારા વિશ્વાસપાત્ર",
      "footer.tagline": "પ્રીમિયમ AI વિડિયો જાહેરાતો",
      "footer.ourServices": "અમારી સેવાઓ",
      "footer.industriesWeServe": "અમે જે ઉદ્યોગોને સેવા આપીએ છીએ",
      "footer.getInTouch": "સંપર્ક કરો",
      "footer.office": "ઓફિસ",
      "common.call": "કૉલ",
      "common.email": "ઈમેલ",
    },
    bn: {
      ...baseTranslations,
      "nav.whyUs": "কেন আমরা",
      "nav.samples": "নমুনা",
      "nav.aiShortFilms": "AI শর্ট ফিল্মস",
      "nav.howItWorks": "কিভাবে কাজ করে",
      "nav.blog": "ব্লগ",
      "hero.title1": "প্রিমিয়াম AI ভিডিও বিজ্ঞাপন",
      "hero.title2": "আপনার ব্যবসার জন্য",
      "hero.subtitle": "এজেন্সিতে লক্ষ টাকা নষ্ট করা বন্ধ করুন। AI দ্বারা চালিত স্টুডিও-মানের ভিডিও বিজ্ঞাপন পান।",
      "hero.trust": "ভারত এবং বিশ্বব্যাপী 10,000+ ব্যবসার বিশ্বাস",
      "footer.tagline": "প্রিমিয়াম AI ভিডিও বিজ্ঞাপন",
      "footer.ourServices": "আমাদের পরিষেবা",
      "footer.industriesWeServe": "আমরা যে শিল্পগুলিতে পরিষেবা দিই",
      "footer.getInTouch": "যোগাযোগ করুন",
      "footer.office": "অফিস",
      "common.call": "কল",
      "common.email": "ইমেইল",
    },
    pa: {
      ...baseTranslations,
      "nav.whyUs": "ਸਾਨੂੰ ਕਿਉਂ",
      "nav.samples": "ਨਮੂਨੇ",
      "nav.aiShortFilms": "AI ਸ਼ਾਰਟ ਫਿਲਮਾਂ",
      "nav.howItWorks": "ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ",
      "nav.blog": "ਬਲੌਗ",
      "hero.title1": "ਪ੍ਰੀਮੀਅਮ AI ਵੀਡੀਓ ਇਸ਼ਤਿਹਾਰ",
      "hero.title2": "ਤੁਹਾਡੇ ਕਾਰੋਬਾਰ ਲਈ",
      "hero.subtitle": "ਏਜੰਸੀਆਂ 'ਤੇ ਲੱਖਾਂ ਬਰਬਾਦ ਕਰਨਾ ਬੰਦ ਕਰੋ। AI ਦੁਆਰਾ ਚਲਾਏ ਸਟੂਡੀਓ-ਗੁਣਵੱਤਾ ਵਾਲੇ ਵੀਡੀਓ ਇਸ਼ਤਿਹਾਰ ਪ੍ਰਾਪਤ ਕਰੋ।",
      "hero.trust": "ਭਾਰਤ ਅਤੇ ਦੁਨੀਆ ਭਰ ਵਿੱਚ 10,000+ ਕਾਰੋਬਾਰਾਂ ਦੁਆਰਾ ਭਰੋਸੇਯੋਗ",
      "footer.tagline": "ਪ੍ਰੀਮੀਅਮ AI ਵੀਡੀਓ ਇਸ਼ਤਿਹਾਰ",
      "footer.ourServices": "ਸਾਡੀਆਂ ਸੇਵਾਵਾਂ",
      "footer.industriesWeServe": "ਅਸੀਂ ਜਿਨ੍ਹਾਂ ਉਦਯੋਗਾਂ ਦੀ ਸੇਵਾ ਕਰਦੇ ਹਾਂ",
      "footer.getInTouch": "ਸੰਪਰਕ ਕਰੋ",
      "footer.office": "ਦਫ਼ਤਰ",
      "common.call": "ਕਾਲ",
      "common.email": "ਈਮੇਲ",
    },
    es: {
      ...baseTranslations,
      "nav.whyUs": "Por Qué Nosotros",
      "nav.samples": "Muestras",
      "nav.aiShortFilms": "Cortometrajes IA",
      "nav.howItWorks": "Cómo Funciona",
      "nav.blog": "Blog",
      "hero.badge.aiPowered": "Impulsado por IA",
      "hero.badge.conversionFocused": "Enfocado en Conversión",
      "hero.badge.globalQuality": "Calidad Global",
      "hero.badge.fastDelivery": "Entrega Rápida",
      "hero.title1": "Anuncios de Video IA Premium",
      "hero.title2": "Para Tu Negocio",
      "hero.subtitle": "Deja de desperdiciar en agencias. Obtén anuncios de video de calidad de estudio de 30 segundos impulsados por IA de vanguardia — más rápido, más inteligente y a una fracción del costo.",
      "hero.trust": "Confiado por más de 10,000 empresas en India y el mundo",
      "hero.emailBtn": "Contactar por Email",
      "hero.callBtn": "Llamar",
      "hero.stats.adsCreated": "Anuncios Creados",
      "hero.stats.fastDelivery": "Entrega Rápida",
      "hero.stats.countries": "Países Atendidos",
      "hero.stats.satisfaction": "Satisfacción",
      "cta.badge": "El Futuro de la Publicidad en Video",
      "cta.title1": "Tus Competidores Ya Están",
      "cta.title2": "Usando Anuncios IA",
      "cta.subtitle": "Cada día que esperas, pierdes clientes ante negocios con mejor contenido de video.",
      "cta.contact": "Contáctanos hoy para anuncios de video IA premium.",
      "cta.whyChoose": "¿Por Qué Elegir edgeaihub?",
      "cta.point1": "Las agencias cobran fortunas — nosotros somos accesibles",
      "cta.point2": "Semanas de espera — entregamos en 24 horas",
      "cta.point3": "Calidad inconsistente — garantizamos output premium",
      "cta.point4": "Procesos complejos — lo hacemos fácil",
      "cta.noCommitments": "Sin compromisos. Solo comienza una conversación.",
      "whyUs.badge": "La Elección Inteligente",
      "whyUs.title": "¿Por Qué",
      "whyUs.subtitle": "Las agencias cobran fortunas. Los freelancers decepcionan. Las herramientas genéricas fallan. Entregamos calidad premium a precios accesibles.",
      "whyUs.agencies.title": "Agencias Tradicionales",
      "whyUs.agencies.point1": "50,000 - 500,000 por video",
      "whyUs.agencies.point2": "2-4 semanas de entrega",
      "whyUs.agencies.point3": "Ciclos de revisión interminables",
      "whyUs.agencies.point4": "Contratos y compromisos complejos",
      "whyUs.freelancers.title": "Freelancers",
      "whyUs.freelancers.point1": "Calidad inconsistente",
      "whyUs.freelancers.point2": "Plazos poco confiables",
      "whyUs.freelancers.point3": "Opciones creativas limitadas",
      "whyUs.freelancers.point4": "Sin escalabilidad",
      "whyUs.genericAI.title": "Herramientas IA Genéricas",
      "whyUs.genericAI.point1": "Output tipo plantilla",
      "whyUs.genericAI.point2": "Sin optimización de anuncios",
      "whyUs.genericAI.point3": "Curva de aprendizaje compleja",
      "whyUs.genericAI.point4": "Tasas de conversión bajas",
      "whyUs.edgeaihub.point1": "Anuncios de video premium accesibles",
      "whyUs.edgeaihub.point2": "Entrega garantizada en 24 horas",
      "whyUs.edgeaihub.point3": "Plantillas optimizadas para conversión",
      "whyUs.edgeaihub.point4": "Escala anuncios ilimitados al instante",
      "trust.badge": "Tu Confianza Importa",
      "trust.title": "Calidad &",
      "trust.titleHighlight": "Confiabilidad",
      "trust.subtitle": "Tomamos tu marca en serio. Cada anuncio pasa por verificaciones rigurosas.",
      "trust.brandSafe.title": "Seguro para Marca",
      "trust.brandSafe.description": "Cada anuncio se revisa para asegurar que se alinee con los valores de tu marca.",
      "trust.qualityChecked.title": "Calidad Verificada",
      "trust.qualityChecked.description": "Aseguramiento de calidad multicapa antes de la entrega.",
      "trust.humanVerified.title": "Verificado por Humanos",
      "trust.humanVerified.description": "IA crea, humanos verifican. La mezcla perfecta.",
      "trust.secureProcess.title": "Proceso Seguro",
      "trust.secureProcess.description": "Tus detalles comerciales se manejan con total confidencialidad.",
      "footer.tagline": "Anuncios de Video IA Premium",
      "footer.description": "Anuncios de Video IA Premium + Cortometrajes IA de calidad Hollywood para marcas globales.",
      "footer.ourServices": "Nuestros Servicios",
      "footer.services.videoAds": "Anuncios de Video IA",
      "footer.services.shortFilms": "Cortometrajes IA",
      "footer.services.brandVideos": "Videos de Marca",
      "footer.services.productAds": "Anuncios de Producto",
      "footer.industriesWeServe": "Industrias que Atendemos",
      "footer.industries.fashion": "Moda y Joyería",
      "footer.industries.ecommerce": "E-commerce",
      "footer.industries.realestate": "Bienes Raíces",
      "footer.industries.education": "Educación",
      "footer.industries.restaurants": "Restaurantes",
      "footer.industries.healthcare": "Salud",
      "footer.getInTouch": "Contáctanos",
      "footer.businessHours": "Lun-Sáb, 9am-8pm IST",
      "footer.office": "Oficina",
      "footer.rights": "Todos los derechos reservados.",
      "footer.aiPowered": "Impulsado por IA",
      "footer.cinemaQuality": "Calidad Cinema",
      "footer.globalService": "Servicio Global",
      "blog.badge": "CENTRO DE CONOCIMIENTO",
      "blog.title": "Marketing de Video IA",
      "blog.titleHighlight": "Blog",
      "blog.subtitle": "Consejos de expertos, estrategias y guías para crear anuncios de video virales y hacer crecer tu negocio",
      "blog.readArticle": "Leer Artículo",
      "blog.backToBlog": "Volver al Blog",
      "blog.relatedArticles": "Artículos Relacionados",
      "blog.ctaTitle": "¿Listo para Crear Tu Propio Anuncio de Video IA?",
      "blog.ctaSubtitle": "Obtén un anuncio de video IA premium con entrega en 24 horas",
      "blog.category.aiMarketing": "Marketing IA",
      "blog.category.socialMedia": "Redes Sociales",
      "blog.category.aiFilms": "Películas IA",
      "blog.category.realEstate": "Bienes Raíces",
      "blog.category.ecommerce": "E-commerce",
      "blog.category.luxury": "Lujo",
      "blog.minRead": "min de lectura",
      "blog.share": "Compartir",
      "common.call": "Llamar",
      "common.email": "Email",
    },
    fr: {
      ...baseTranslations,
      "nav.whyUs": "Pourquoi Nous",
      "nav.samples": "Échantillons",
      "nav.aiShortFilms": "Courts Métrages IA",
      "nav.howItWorks": "Comment Ça Marche",
      "nav.blog": "Blog",
      "hero.title1": "Publicités Vidéo IA Premium",
      "hero.title2": "Pour Votre Entreprise",
      "hero.subtitle": "Arrêtez de gaspiller en agences. Obtenez des publicités vidéo de qualité studio de 30 secondes propulsées par l'IA — plus rapide, plus intelligent et à moindre coût.",
      "hero.trust": "Fait confiance par plus de 10 000 entreprises en Inde et dans le monde",
      "cta.badge": "L'Avenir de la Publicité Vidéo",
      "cta.title1": "Vos Concurrents Utilisent Déjà",
      "cta.title2": "Les Publicités IA",
      "footer.tagline": "Publicités Vidéo IA Premium",
      "footer.ourServices": "Nos Services",
      "footer.industriesWeServe": "Industries Que Nous Servons",
      "footer.getInTouch": "Contactez-Nous",
      "footer.office": "Bureau",
      "footer.rights": "Tous droits réservés.",
      "blog.badge": "CENTRE DE CONNAISSANCES",
      "blog.title": "Marketing Vidéo IA",
      "blog.titleHighlight": "Blog",
      "blog.subtitle": "Conseils d'experts, stratégies et guides pour créer des publicités vidéo virales et développer votre entreprise",
      "blog.readArticle": "Lire l'Article",
      "blog.backToBlog": "Retour au Blog",
      "blog.relatedArticles": "Articles Connexes",
      "blog.ctaTitle": "Prêt à Créer Votre Propre Publicité Vidéo IA?",
      "blog.ctaSubtitle": "Obtenez une publicité vidéo IA premium avec livraison en 24 heures",
      "blog.category.aiMarketing": "Marketing IA",
      "blog.category.socialMedia": "Réseaux Sociaux",
      "blog.category.aiFilms": "Films IA",
      "blog.category.realEstate": "Immobilier",
      "blog.category.ecommerce": "E-commerce",
      "blog.category.luxury": "Luxe",
      "blog.minRead": "min de lecture",
      "blog.share": "Partager",
      "common.call": "Appeler",
      "common.email": "Email",
    },
    de: {
      ...baseTranslations,
      "nav.whyUs": "Warum Wir",
      "nav.samples": "Beispiele",
      "nav.aiShortFilms": "KI Kurzfilme",
      "nav.howItWorks": "Wie Es Funktioniert",
      "nav.blog": "Blog",
      "hero.title1": "Premium KI Video-Werbung",
      "hero.title2": "Für Ihr Unternehmen",
      "hero.subtitle": "Hören Sie auf, bei Agenturen zu verschwenden. Erhalten Sie KI-gestützte Videoads in Studioqualität — schneller, intelligenter und günstiger.",
      "hero.trust": "Vertraut von über 10.000 Unternehmen in Indien und weltweit",
      "cta.badge": "Die Zukunft der Videowerbung",
      "cta.title1": "Ihre Konkurrenten Nutzen Bereits",
      "cta.title2": "KI-Werbung",
      "footer.tagline": "Premium KI Video-Werbung",
      "footer.ourServices": "Unsere Dienstleistungen",
      "footer.industriesWeServe": "Branchen Die Wir Bedienen",
      "footer.getInTouch": "Kontaktieren Sie Uns",
      "footer.office": "Büro",
      "footer.rights": "Alle Rechte vorbehalten.",
      "common.call": "Anrufen",
      "common.email": "E-Mail",
    },
    ar: {
      ...baseTranslations,
      "nav.whyUs": "لماذا نحن",
      "nav.samples": "عينات",
      "nav.aiShortFilms": "أفلام قصيرة بالذكاء الاصطناعي",
      "nav.howItWorks": "كيف يعمل",
      "nav.blog": "مدونة",
      "hero.title1": "إعلانات فيديو بالذكاء الاصطناعي",
      "hero.title2": "لعملك",
      "hero.subtitle": "توقف عن إهدار الأموال على الوكالات. احصل على إعلانات فيديو بجودة الاستوديو مدعومة بالذكاء الاصطناعي — أسرع وأذكى وبتكلفة أقل.",
      "hero.trust": "موثوق به من قبل أكثر من 10,000 شركة في الهند والعالم",
      "cta.badge": "مستقبل إعلانات الفيديو",
      "cta.title1": "منافسوك يستخدمون بالفعل",
      "cta.title2": "إعلانات الذكاء الاصطناعي",
      "footer.tagline": "إعلانات فيديو بالذكاء الاصطناعي",
      "footer.ourServices": "خدماتنا",
      "footer.industriesWeServe": "الصناعات التي نخدمها",
      "footer.getInTouch": "تواصل معنا",
      "footer.office": "المكتب",
      "footer.rights": "جميع الحقوق محفوظة.",
      "blog.badge": "مركز المعرفة",
      "blog.title": "تسويق الفيديو بالذكاء الاصطناعي",
      "blog.titleHighlight": "مدونة",
      "blog.subtitle": "نصائح واستراتيجيات وأدلة خبراء لإنشاء إعلانات فيديو فيروسية وتنمية عملك",
      "blog.readArticle": "اقرأ المقال",
      "blog.backToBlog": "العودة إلى المدونة",
      "blog.relatedArticles": "مقالات ذات صلة",
      "blog.ctaTitle": "هل أنت مستعد لإنشاء إعلان فيديو AI خاص بك؟",
      "blog.ctaSubtitle": "احصل على إعلان فيديو AI متميز مع التسليم خلال 24 ساعة",
      "blog.category.aiMarketing": "تسويق AI",
      "blog.category.socialMedia": "وسائل التواصل الاجتماعي",
      "blog.category.aiFilms": "أفلام AI",
      "blog.category.realEstate": "العقارات",
      "blog.category.ecommerce": "التجارة الإلكترونية",
      "blog.category.luxury": "الفخامة",
      "blog.minRead": "دقائق للقراءة",
      "blog.share": "مشاركة",
      "common.call": "اتصل",
      "common.email": "بريد إلكتروني",
    },
    zh: {
      ...baseTranslations,
      "nav.whyUs": "为什么选择我们",
      "nav.samples": "样品",
      "nav.aiShortFilms": "AI短片",
      "nav.howItWorks": "如何运作",
      "nav.blog": "博客",
      "hero.title1": "优质AI视频广告",
      "hero.title2": "为您的企业",
      "hero.subtitle": "停止在代理商上浪费大量资金。获取由尖端AI驱动的30秒工作室级视频广告——更快、更智能、成本更低。",
      "hero.trust": "受到印度和全球10,000多家企业的信赖",
      "cta.badge": "视频广告的未来",
      "cta.title1": "您的竞争对手已经在",
      "cta.title2": "使用AI广告",
      "footer.tagline": "优质AI视频广告",
      "footer.ourServices": "我们的服务",
      "footer.industriesWeServe": "我们服务的行业",
      "footer.getInTouch": "联系我们",
      "footer.office": "办公室",
      "footer.rights": "版权所有。",
      "blog.badge": "知识中心",
      "blog.title": "AI视频营销",
      "blog.titleHighlight": "博客",
      "blog.subtitle": "专家提示、策略和指南，帮助您创建病毒式视频广告并发展业务",
      "blog.readArticle": "阅读文章",
      "blog.backToBlog": "返回博客",
      "blog.relatedArticles": "相关文章",
      "blog.ctaTitle": "准备好创建您自己的AI视频广告了吗？",
      "blog.ctaSubtitle": "获取24小时交付的高级AI视频广告",
      "blog.category.aiMarketing": "AI营销",
      "blog.category.socialMedia": "社交媒体",
      "blog.category.aiFilms": "AI电影",
      "blog.category.realEstate": "房地产",
      "blog.category.ecommerce": "电子商务",
      "blog.category.luxury": "奢侈品",
      "blog.minRead": "分钟阅读",
      "blog.share": "分享",
      "common.call": "致电",
      "common.email": "邮箱",
    },
    ja: {
      ...baseTranslations,
      "nav.whyUs": "なぜ私たちを",
      "nav.samples": "サンプル",
      "nav.aiShortFilms": "AIショートフィルム",
      "nav.howItWorks": "仕組み",
      "nav.blog": "ブログ",
      "hero.title1": "プレミアムAI動画広告",
      "hero.title2": "あなたのビジネスのために",
      "hero.subtitle": "代理店に大金を使うのをやめましょう。最先端AIによるスタジオ品質の30秒動画広告を入手—より速く、よりスマートに、低コストで。",
      "hero.trust": "インドと世界中の10,000以上の企業から信頼されています",
      "cta.badge": "動画広告の未来",
      "cta.title1": "あなたの競合他社はすでに",
      "cta.title2": "AI広告を使用しています",
      "footer.tagline": "プレミアムAI動画広告",
      "footer.ourServices": "サービス",
      "footer.industriesWeServe": "対応業界",
      "footer.getInTouch": "お問い合わせ",
      "footer.office": "オフィス",
      "footer.rights": "全著作権所有。",
      "blog.badge": "ナレッジハブ",
      "blog.title": "AI動画マーケティング",
      "blog.titleHighlight": "ブログ",
      "blog.subtitle": "バイラル動画広告を作成しビジネスを成長させるための専門家のヒント、戦略、ガイド",
      "blog.readArticle": "記事を読む",
      "blog.backToBlog": "ブログに戻る",
      "blog.relatedArticles": "関連記事",
      "blog.ctaTitle": "自分だけのAI動画広告を作成する準備はできましたか？",
      "blog.ctaSubtitle": "24時間配信のプレミアムAI動画広告を入手",
      "blog.category.aiMarketing": "AIマーケティング",
      "blog.category.socialMedia": "ソーシャルメディア",
      "blog.category.aiFilms": "AI映画",
      "blog.category.realEstate": "不動産",
      "blog.category.ecommerce": "Eコマース",
      "blog.category.luxury": "ラグジュアリー",
      "blog.minRead": "分で読める",
      "blog.share": "共有",
      "common.call": "電話",
      "common.email": "メール",
    },
    ko: {
      ...baseTranslations,
      "nav.whyUs": "왜 우리인가",
      "nav.samples": "샘플",
      "nav.aiShortFilms": "AI 단편 영화",
      "nav.howItWorks": "작동 방식",
      "nav.blog": "블로그",
      "hero.title1": "프리미엄 AI 비디오 광고",
      "hero.title2": "당신의 비즈니스를 위해",
      "hero.subtitle": "에이전시에 돈을 낭비하지 마세요. 최첨단 AI로 구동되는 스튜디오 품질의 30초 비디오 광고를 받으세요 — 더 빠르게, 더 스마트하게, 저렴하게.",
      "hero.trust": "인도와 전 세계 10,000개 이상의 비즈니스가 신뢰합니다",
      "cta.badge": "비디오 광고의 미래",
      "cta.title1": "경쟁업체는 이미",
      "cta.title2": "AI 광고를 사용하고 있습니다",
      "footer.tagline": "프리미엄 AI 비디오 광고",
      "footer.ourServices": "서비스",
      "footer.industriesWeServe": "서비스 산업",
      "footer.getInTouch": "연락하기",
      "footer.office": "사무실",
      "footer.rights": "모든 권리 보유.",
      "common.call": "전화",
      "common.email": "이메일",
    },
    pt: {
      ...baseTranslations,
      "nav.whyUs": "Por Que Nós",
      "nav.samples": "Amostras",
      "nav.aiShortFilms": "Curtas de IA",
      "nav.howItWorks": "Como Funciona",
      "nav.blog": "Blog",
      "hero.title1": "Anúncios de Vídeo IA Premium",
      "hero.title2": "Para o Seu Negócio",
      "hero.subtitle": "Pare de desperdiçar em agências. Obtenha anúncios de vídeo de qualidade de estúdio de 30 segundos impulsionados por IA — mais rápido, mais inteligente e mais barato.",
      "hero.trust": "Confiado por mais de 10.000 empresas na Índia e no mundo",
      "cta.badge": "O Futuro da Publicidade em Vídeo",
      "cta.title1": "Seus Concorrentes Já Estão",
      "cta.title2": "Usando Anúncios IA",
      "footer.tagline": "Anúncios de Vídeo IA Premium",
      "footer.ourServices": "Nossos Serviços",
      "footer.industriesWeServe": "Indústrias que Atendemos",
      "footer.getInTouch": "Entre em Contato",
      "footer.office": "Escritório",
      "footer.rights": "Todos os direitos reservados.",
      "common.call": "Ligar",
      "common.email": "E-mail",
    },
    ru: {
      ...baseTranslations,
      "nav.whyUs": "Почему Мы",
      "nav.samples": "Образцы",
      "nav.aiShortFilms": "ИИ Короткометражки",
      "nav.howItWorks": "Как Это Работает",
      "nav.blog": "Блог",
      "hero.title1": "Премиум ИИ Видеореклама",
      "hero.title2": "Для Вашего Бизнеса",
      "hero.subtitle": "Перестаньте тратить деньги на агентства. Получите 30-секундную видеорекламу студийного качества на базе ИИ — быстрее, умнее и дешевле.",
      "hero.trust": "Нам доверяют более 10 000 компаний в Индии и по всему миру",
      "cta.badge": "Будущее Видеорекламы",
      "cta.title1": "Ваши Конкуренты Уже",
      "cta.title2": "Используют ИИ Рекламу",
      "footer.tagline": "Премиум ИИ Видеореклама",
      "footer.ourServices": "Наши Услуги",
      "footer.industriesWeServe": "Отрасли Которые Мы Обслуживаем",
      "footer.getInTouch": "Свяжитесь С Нами",
      "footer.office": "Офис",
      "footer.rights": "Все права защищены.",
      "common.call": "Звонок",
      "common.email": "Эл. почта",
    },
    it: {
      ...baseTranslations,
      "nav.whyUs": "Perché Noi",
      "nav.samples": "Campioni",
      "nav.aiShortFilms": "Cortometraggi IA",
      "nav.howItWorks": "Come Funziona",
      "nav.blog": "Blog",
      "hero.title1": "Annunci Video IA Premium",
      "hero.title2": "Per la Tua Attività",
      "hero.subtitle": "Smetti di sprecare soldi in agenzie. Ottieni annunci video di qualità studio di 30 secondi alimentati dall'IA — più veloci, più intelligenti e più economici.",
      "hero.trust": "Fidato da oltre 10.000 aziende in India e nel mondo",
      "cta.badge": "Il Futuro della Pubblicità Video",
      "cta.title1": "I Tuoi Concorrenti Stanno Già",
      "cta.title2": "Usando Annunci IA",
      "footer.tagline": "Annunci Video IA Premium",
      "footer.ourServices": "I Nostri Servizi",
      "footer.industriesWeServe": "Settori Che Serviamo",
      "footer.getInTouch": "Contattaci",
      "footer.office": "Ufficio",
      "footer.rights": "Tutti i diritti riservati.",
      "common.call": "Chiama",
      "common.email": "Email",
    },
  };
  
  return translations[lang] || translations.en;
};
